sh sh_control_exp_compressNCA_nocur.sh ablation_nca_ts80 ablation_nca_ts80.yaml;
sh sh_control_exp_compressNCA_nocur.sh ablation_nca_ts120 ablation_nca_ts120.yaml;
sh sh_control_exp_compressNCA_nocur.sh ablation_nca_ts160 ablation_nca_ts160.yaml
