---
#Lista de parametros para teste
exp_name: 'exp_hello'
path_input_img: 'data/urso.jpg'


# Number of CA state channels
CHANNEL_N: 16
#Number of pixels used to pad the target image border
TARGET_PADDING: 0
TARGET_SIZE: 20
hidden_size: 42
initial_target_size: 10
target_increase: 10

lr: 0.002
lr_gamma: 0.9999
n_epoch: 300

BATCH_SIZE: 8
POOL_SIZE: 1024
CELL_FIRE_RATE: 0.5 

EXPERIMENT_TYPE: "Growing"
output_folder: 'outputs'