---
#Lista de parametros para teste
exp_name: 'urso_nca_ts60_hs62_step112_144_ep20k'
path_input_img: 'data/urso.jpg'


# Number of CA state channels
CHANNEL_N: 16
#Number of pixels used to pad the target image border
TARGET_PADDING: 0
TARGET_SIZE: 60
hidden_size: 62

step_min: 112
step_max: 144

lr: 0.002
lr_gamma: 0.9999
n_epoch: 20000

BATCH_SIZE: 8
POOL_SIZE: 1024
CELL_FIRE_RATE: 0.5 

EXPERIMENT_TYPE: "Growing"
output_folder: 'outputs'